FROM clickhouse/clickhouse-server:26.3

RUN mkdir -p /cdr-source/cdr \
    && chown -R clickhouse:clickhouse /cdr-source

COPY clickhouse/config.d/ /etc/clickhouse-server/config.d/
COPY clickhouse/init/ /docker-entrypoint-initdb.d/
COPY clickhouse/users.d/ /etc/clickhouse-server/users.d/
